use bump version args action

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -67,17 +67,15 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-
-      # - name: Setup project
-      #   uses: ./.github/actions/project-setup
       
       - name: Get current version
         id: current_version
         uses: mozilla-ai/cargo-goose/actions/current-version@v1
         with:
           force-single-version: true
-
-      - name: Bump version
+      
+      - name: Compute cargo-goose args
+        id: goose_args
         run: |
           ACTION="${{ github.event.inputs.action }}"
           LEVEL="${{ github.event.inputs.level }}"
@@ -85,21 +83,56 @@ jobs:
 
           case "$ACTION" in
             bump-version)
-              cargo goose bump version "$LEVEL"
+              ARGS="bump version $LEVEL"
               ;;
             start-prerelease)
-              cargo goose bump version "$LEVEL" "$STAGE"
+              ARGS="bump version $LEVEL $STAGE"
               ;;
             bump-prerelease)
-              cargo goose bump prerelease
+              ARGS="bump prerelease"
               ;;
             transition-prerelease)
-              cargo goose bump prerelease "$STAGE"
+              ARGS="bump prerelease $STAGE"
               ;;
             finalize)
-              cargo goose bump release
+              ARGS="bump release"
+              ;;
+            *)
+              echo "Invalid action"
+              exit 1
               ;;
           esac
+
+          echo "args=$ARGS" >> "$GITHUB_OUTPUT"
+
+      - name: Bump version
+        uses: mozilla-ai/cargo-goose/actions/cargo-goose@v1
+        with:
+          args: ${{ steps.goose_args.outputs.args }}
+
+      # - name: Bump version
+      #   run: |
+      #     ACTION="${{ github.event.inputs.action }}"
+      #     LEVEL="${{ github.event.inputs.level }}"
+      #     STAGE="${{ github.event.inputs.stage }}"
+
+      #     case "$ACTION" in
+      #       bump-version)
+      #         cargo goose bump version "$LEVEL"
+      #         ;;
+      #       start-prerelease)
+      #         cargo goose bump version "$LEVEL" "$STAGE"
+      #         ;;
+      #       bump-prerelease)
+      #         cargo goose bump prerelease
+      #         ;;
+      #       transition-prerelease)
+      #         cargo goose bump prerelease "$STAGE"
+      #         ;;
+      #       finalize)
+      #         cargo goose bump release
+      #         ;;
+      #     esac
 
       - name: Get new version
         id: new_version
